CREATE DATABASE DFMS;

USE DFMS;

CREATE TABLE `ADMIN`(
    ADMIN_ID 	VARCHAR(20) PRIMARY KEY,
	PASSWD 		VARCHAR(100),
	JOIN_DT 	DATETIME
);

INSERT INTO `ADMIN` VALUES ('dfmsadmin' , 'halfood24' , NOW());

CREATE TABLE ADMIN_NOTICE (
    NOTICE_CD 		 INT AUTO_INCREMENT PRIMARY KEY,
	CONTENT			 VARCHAR(2000),
	SUBJECT 		 VARCHAR(50),
	ENROLL_DT 		 DATETIME
);

CREATE TABLE MEMBER(
    MEMBER_ID 		VARCHAR(50) PRIMARY KEY,
	MEMBER_NM 		VARCHAR(50),
    PASSWD 			VARCHAR(1000),
	DATE_BIRTH 		VARCHAR(20),
	HP 				VARCHAR(20),
	SMSSTS_YN 		VARCHAR(20),
	EMAIL 			VARCHAR(20),
	EMAILSTS_YN 	VARCHAR(20),
	ZIPCODE 		VARCHAR(20),
	ROAD_ADDRESS 	VARCHAR(500),
	JIBUN_ADDRESS 	VARCHAR(500),
	NAMUJI_ADDRESS 	VARCHAR(500),
	POINT			INT,
	JOIN_DT 		DATETIME
);

CREATE TABLE GOODS(
    GOODS_CD 		  INT AUTO_INCREMENT PRIMARY KEY,
    GOODS_NM 		  VARCHAR(500),
    SORT 			  VARCHAR(200),
	PRICE 			  INT,
	DISCOUNT_RATE 	  INT,
	TOTAL_AMOUNT 	  INT,
    KCAL			  INT,
    PROTEIN_CONTENT	  INT,
    PRODUCER		  VARCHAR(50),
    PRODUCTION_DT	  DATE,
    EXPIRATION_DT	  DATE,
	STOCK			  INT,
	NUTRITIONAL_INFO  VARCHAR(2000),
    MATERIAL_CONTENT  VARCHAR(2000),
    PRECAUTION		  VARCHAR(2000),
	POINT 			  INT,
	DELIVERY_PRICE 	  INT,
	PART 			  VARCHAR(50),
	GOODS_FILE_NAME	  VARCHAR(2000),
	ENROLL_DT 		  DATETIME
);

CREATE TABLE `ORDER`(
	ORDER_CD 			INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID 			VARCHAR(20),
    GOODS_CD 			INT,
	ORDER_GOODS_QTY 	INT,
	PAYMENT_AMT			INT,
    ORDERER_NM 			VARCHAR(50),
    ORDERER_HP 			VARCHAR(50),
	ZIPCODE 			VARCHAR(20),
	ROAD_ADDRESS 		VARCHAR(500),
	JIBUN_ADDRESS 		VARCHAR(500),
	NAMUJI_ADDRESS 		VARCHAR(500),
    DELIVERY_METHOD 	VARCHAR(40),
    DELIVERY_MESSAGE 	VARCHAR(300),
    DELIVERY_STATUS 	VARCHAR(100),
	PAY_METHOD 			VARCHAR(200),
	PAY_ORDERER_HP 		VARCHAR(50), 
	CARD_COMPANY_NM 	VARCHAR(50),
	CARD_PAY_MONTH 		VARCHAR(20),
    PAY_ORDER_TIME 		DATETIME
);

CREATE TABLE CART (
	CART_CD   	   INT AUTO_INCREMENT PRIMARY KEY,
	MEMBER_ID 	   VARCHAR(20),
	GOODS_CD  	   INT,
	CART_GOODS_QTY INT,
	ENROLL_DT 	   DATETIME
);


CREATE TABLE HEART (
	HEART_CD   	  	INT AUTO_INCREMENT PRIMARY KEY,
	MEMBER_ID 	   	VARCHAR(20),
	GOODS_CD  	   	INT,
	HEART_GOODS_QTY	INT
);

CREATE TABLE CONTACT (
	CONTACT_CD  INT AUTO_INCREMENT PRIMARY KEY,
	NAME		VARCHAR(50),
	EMAIL		VARCHAR(50),
	SUBJECT		VARCHAR(300),
	CONTENT		VARCHAR(2000),
	REG_DT  	DATETIME
);
